### ISSUE TITLE
Including callback for transferring MWDI information to NewRelease during bequeathing process

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AutomatedLinkAcceptanceProxy#105]
As per understanding, AutomatedLinkAcceptanceProxy (ALAP) requires the details of MWDI (MicrowaveDeviceInventory) for accessing the device data which is present as client ltps in config file.

During bequeath-your-data-and-die process, shall we include a callback that could transfer the MWDI data from OldRelease to NewRelease. 

However we could update the data through fake-ip-script, since automated process would be preferred in ApplicationPattern for updating an application's data through rest APIs, kindly please let us know your views in this regards.

**Comment by kmohr-soprasteria** [comment]
I don't think we are storing any data (no ElasticSearch client-stack, also no fileProfile). So I don't think we will be transferring any device data to a new release.

@IswaryaaS: or are you referring to the connection details for MWDI like ip/port etc.?

**Comment by IswaryaaS** [comment]
Yeah, I am referring to MWDI because ALAP is very much dependent on MWDI, so the transfer of its protocol, ip-address and port data would be useful.

**Comment by kmohr-soprasteria** [comment]
Hi Iswaryaa, actually I thought that information of applications that remains in the serviceList is transferred anyway, as it will be kept in the configFile/loadFile and was not aware that we need a callback for that.
So from my side it sounds reasonable to include the callback.

**Comment by IswaryaaS** [comment]
As per my understanding, fake-ip script is a temporary method for translating address and port information of an application in a configFile. Usually if we refer to any one of TAC applications, all the details of an application like "ip-address", "port", "release-number", any "subscribed operation" or sometimes the "whole application" gets transferred to the new version of an application through in callback during bequeath-your-data-and-die. 

This enables the whole data transfer from old version to new version of the application automated , avoiding any human or script intervention. 

Example: kindly check PromptForBequeathingDataCausesTransferOfListOfApplications callback in [OAS of EATL](https://github.com/openBackhaul/ExecutionAndTraceLog/blob/develop/spec/ExecutionAndTraceLog.yaml). This callback transfers the list of all applications (and their corresponding information) to new version

Anyway, fake-ip script is an easy way for updating the data. 

_Just that I would like to know the view on this aspect that if it is fine to use fake-ip-script instead of callback._

**Comment by openBackhaul** [comment]
While initially putting AutomatedLinkAcceptanceProxy into operation, TCP/IP address information of MicroWaveDeviceInventory has to be written by fake-ip script into the CONFIGfile.
Same in case of updating AutomatedLinkAcceptanceProxy.
In case of updating MicroWaveDeviceInventory, new address information will be received via broadcast from RegistryOffice.

So, no change required.
