### ISSUE TITLE
type of "enumeration" in string-profile schema shall be changed to "array"

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AutomatedLinkAcceptanceProxy#108]
As per https://github.com/openBackhaul/ApplicationPattern/issues/556, the the "enumeration" attribute needs to be updated to "type: array" instead of "type: string" in all occurrences.

Note : As of now , in the server side generated yaml file , manually we updated the type of enumeration to "array"(as described in this https://github.com/openBackhaul/ApplicationPattern/issues/556) to resolve the error.

**Comment by kmohr-soprasteria** [comment]
See change in MWDI oas for reference:
![image](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/assets/57349523/a910efe2-0d08-4589-afd4-c28d08d649fe)
