### ISSUE TITLE
To ignore "server" folder in the .github/workflows/yaml-lint.yaml rules

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AutomatedLinkAcceptanceProxy#113]
To ignore the ./server/api/openapi.yaml file from the yaml-lint validation , rules in the .github/workflows/yaml-lint.yaml shall be modified to ignore the folder server.
```yaml
ignore: |
   server/
```

**Comment by anacabbar** [comment]
Hi @PrathibaJee, let me know if #115 correctly solved this issue

**Comment by PrathibaJee** [comment]
Hi @anacabbar , yes it is. Many thanks for doing the needful.
