### ISSUE TITLE
Request to dissolve few forwarding's that contain multiple consequent requests 

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/AutomatedLinkAcceptanceProxy#122]
Callback "RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole" consists of a list of consequent requests that needs to be performed to fetch the OriginalLtpName , VlanInterfaceKind , EthernetContainerStatus. 

For this , we have the forwarding-construct "RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole" using which we can get operation-clients.

**Problem Description :** 

During Implementation, since all three operation-clients (each pointing to different sub-callbacks i.e., one for originalLtpName, one for VlanInterfaceKind and the other for EthernetContainerStatus) are present in OUTPUT fc-port list of same forwarding-construct, it would be difficult for choosing the exact OUTPUT fc-port for a sub-callback .

And to do so , we have to hardcode the indexes like

- output-fc-port[0] = originalLtpName.
- output-fc-port[1] = vlanInterfaceKind.
- output-fc-port[2] = EthernetContainerStatus.

But,this would work fine until the indexes in the config file are intact without any change.
 
In future, if there is any change in this index in config file, it would lead to errored response and requires changes in the implementation everytime there is change in config file indexes which leads to tight coupling of implementation and config file.

**Proposal :** 
Request to dissolve forwarding-construst RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole into 3 forwarding as mentioned below : 

- RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole.OriginalLtpName 
- RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole.VlanInterfaceKind
- RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole.EthernetContainerStatus 

from this we can avoid the hardcoding of the indexes and any future complications. 

If the above proposal is accepted then the same can be adapted for below mentioned forwarding-construct's as well:

- RequestForProvidingAcceptanceDataCausesDeterminingTheWanPortRole
- RequestForProvidingAcceptanceDataCausesRetrievingSfpInformation
- RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition
- RequestForProvidingAcceptanceDataCausesDeterminingTheOduConnector

**Comment by anacabbar** [comment]
As I understand it, it would be okay to hard-code the uuids of the StringProfileInstances, since this allows identifying which query parameter is required for each operation and the StringValue of the referenced StringProfileInstance remains configurable.

There is one StringProfileInstance uniquely and specifically defined for each and every callback request to the MWDI, so I believe it is okay to link them through hard-coded uuids.

Is there a downside to doing this?

**Comment by vanithavalluripalli9** [comment]
Hi Ana , Thank you for looking into the issue. 

I would like to apologize for the earlier confusion .  I have updated the issue in the description it will not only lead for the hardcoding of string profile uuid's but also hard coding the indexes .

Kindly look into the issue and let us know your doubts.

**Comment by anacabbar** [comment]
Hi Vanitha, thank you for the comment and the detailed explanation. 

I see now what the problem is. We could dissolve the forwardings, but couldn't the LocalID values of the fc-ports also be used to associate the fc-ports to the SubCallbacks as an alternative to indexes? Something like

output-fc-port.localID=='200'  =  originalLtpName

**Comment by vanithavalluripalli9** [comment]
Hi Ana, Thank you for the comment.

But , hardocding the localid also will lead to the same problem as mentioned 

In future, if there is any change in this localid in config file, it would lead to errored response and requires changes in the implementation everytime there is change in config file localid which leads to tight coupling of implementation and config file.

Also, hardcoding the localId might not be a good coding practice.

**Comment by anacabbar** [comment]
Many thanks Vanitha for the explanation. The listed forwardings will be dissolved as requested.
