### ISSUE TITLE
Clarification regarding formulation of parameters for position-of-modem-board attrbiute

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/AutomatedLinkAcceptanceProxy#144]
**Please note that the below mentioned issue is need for clarification issue** 

As per OAS , below is the description present to formulate the parameters of position-of-modem-board : 

 ```
position-of-modem-board:
    type: string
    description: >
      'Provided for split mount devices only
      Identifier of the slot that holds the link end point according to the currently valid, official documentation of the equipment
          Starting from the AirInterface that is identified by UuidUnderTest determined in 
      RequestForProvidingAcceptanceDataCausesDeterminingAirInterfaceUuidUnderTest
          the underlaying equipment has to be identified by 
      RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.EquipmentUuid.response.body#ltp-augment-1-0:ltp-augment-pac/equipment
          for each of the EquipmentUuids the category has to be retrieved by 
      RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.EquipmentCategory.response.by#core-model-1-4:actual-equipment/structure/category
          for the single EquipmentUuid with RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.EquipmentCategory.response.by#core-model-1-4:actual-equipment/structure/category == equipment-augment-1-0:EQUIPMENT_CATEGORY_MODEM
          from RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel.response.body#core-model-1-4:control-construct/equipment/contained-holder/equipment-augment-1-0:holder-pac/vendor-label'

```
**Query Description :** 

As per the description , we implemented the below mentioned steps to formulate the position-of-modem-board : 

-  Fetched the equipment list for the air-interface uuid under test by using the callback RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition. EquipmentUuid.
- For each of the EquipmentUuids,Performed the callback RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition. EquipmentCategory and found out the equipment category.
- If the core-model-1-4:actual-equipment/structure/category == equipment-augment-1-0:EQUIPMENT_CATEGORY_MODEM, then performed the callback RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel.
- Then from  response body of RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel.response.body#core-model-1-4:control-construct/equipment/contained-holder/equipment-augment-1-0:holder-pac/vendor-label'  we formulated the position-of-modem-board

**Query :** 

After implementation , during testing, we came across a scenario in one of the ericsson devices in testlab , where RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel.response.body#core-model-1-4:control-construct/equipment/contained-holder is a list and each contained-holder consists of vendor label , which means we can fetch list of vendor-label's instead of one.

Could you please , kindly let us know on how to proceed in the above scenario where there are multiple container-holders.

**Comment by vanithavalluripalli9** [comment]
Update regarding implementation : 

As we are not sure on how to fetch the response if container holder is a list,  as a temporary solution for this in implemetation we convereted the list to string and fetching the response.

**Comment by anacabbar** [comment]
The two entries of the list contained-holder correspond to the two RF-Ports of the Modem Board (MMU). 
Example: 
First  item of the list contained-holder
![image](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/assets/116157436/2212d4d2-63c5-4b48-ab99-6fa30586ead7)
Second item of the list contained-holder:
![image](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/assets/116157436/b969fca1-11d4-4ff5-80ad-b8026e875cbc)
![image](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/assets/116157436/c146e177-d287-4ef6-8b1b-4febb31f0c17)
It has to be clarified if/how it is possible to identify which of the two corresponds to the air interface under test. If not possible, then change specification so that a list of vendor labels is delivered as response.

Also to be checked what the response looks like for other vendors when the equipment augment has been successfully implemented by all

**Comment by anacabbar** [comment]
* This is way to identify the correct object in containedHolder (i.e. which RF-Port in the modem board is the one used for connecting the outdoor unit):
  
   1. Fetch the equipment list for the air-interface uuid under test by using the callback RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition. EquipmentUuid.
   2. For each of the EquipmentUuids, performe the callback RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition. EquipmentCategory and find out the equipment category.	
             ( In case of a split-mount, the equipment listed under the LtpAugmentPac of the AirInterface will either be of the category "equipment-augment-1-0:EQUIPMENT_CATEGORY_OUTDOOR_UNIT"
	    or "equipment-augment-1-0:EQUIPMENT_CATEGORY_MODEM")
    
   3.  If the core-model-1-4:actual-equipment/structure/category == equipment-augment-1-0:EQUIPMENT_CATEGORY_MODEM, then perform the callback _RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel._ 	
    
	     **Each object in the list containedHolder has the attribute "occupying-fru", which is referencing the uuid of the associated outdoor unit. 
	     The correct object is the one which references the uuid of the outdoor unit listed in the LtpAugment of the AirInterfaceUnderTest**



* This is in compliance with Chapter 6 of the Transmitter Equipment Specification (Instantiation. Equipment and Holder)

	
* A better explanation of this procedure must be added to the the description of  "position-of-modem-board" in the OAS

**Comment by anacabbar** [comment]
StringProfileInstance required for successfully being able to execute the callback RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel has been updated as describied in #197
