### ISSUE TITLE
Add indication of currently active firmware

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/AutomatedLinkAcceptanceProxy#184]
Feature request addressed by Tim Gradel.

**Problem:**
Currently the ALAP is providing information about the firmware on the device.
It regards all banks, but it does not indicate the currently active bank.

**Solution:**
Information about the currently active firmware shall be added to the responseBody of /v1/provide-acceptance-data-of-link-endpoint.

**Comment by anacabbar** [comment]
ALAP is already providing information about the active/standBy status of the Firmware Components. Example:

"installed-firmware": [
            {
                "firmware-component-name": "Web Server LCT",
                "firmware-component-version": "N96129  01.10.02",
                **"firmware-component-status": "firmware-1-0:FIRMWARE_COMPONENT_STATUS_TYPE_ACTIVE"**
            },
            {
                "firmware-component-name": "Boot",
                "firmware-component-version": "E82118  01.00.00",
                **"firmware-component-status": "firmware-1-0:FIRMWARE_COMPONENT_STATUS_TYPE_ACTIVE"**
            },
            {
                "firmware-component-name": "IDU Board Bench 2",
                "firmware-component-version": "N60052 01.10.02",
                **"firmware-component-status": "firmware-1-0:FIRMWARE_COMPONENT_STATUS_TYPE_ACTIVE"**
            },
            {
                "firmware-component-name": "IDU Board Bench 1",
                "firmware-component-version": "N60052 01.10.02",
                **"firmware-component-status": "firmware-1-0:FIRMWARE_COMPONENT_STATUS_TYPE_STAND_BY"**
            }
        ]

Ticket has to be opened in APT, in order for LinkVis to make use of these available but unused Status Informations.
