### ISSUE TITLE
Asynchronous /v1/provide-acceptance-data-of-link-endpoint

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/AutomatedLinkAcceptanceProxy#186]
Executing the ALAP://v1/provide-acceptance-data-of-link-endpoint service has been measured by Andreas' Postman request collection to last ~20s. 

Please double check before changing the specification, if this would be reproducible, making the service asynchronous should be evaluated.

Instead of answering the entire acceptance data in its ResponseBody, the service should confirm the receipt and processability of the request and name a process number. 
The result of the ~100Requests long processing of the request should then be sent to APT in a separate callback also containing the same process number.

Feasibility of sending this callback to APT should be clarified with Mentopolis first.

An example for an asynchronous service definition and its callback could be found in e.g. AIPS://v1/switch-redundant-transmitter-pair-off .

Sending the response address in every requestBody should be replaced by a separate service.
Reasons: ALAP shall implement a 1:1 relationship with APT => Facilitating sending to individual clients is not required.
Configuring the APT address inside ALAP exclusively via OaM would make APT dependent on the MW SDN operation.
A separate service applicable with their username/password allows them to configure the interface independently.
Due to latest experiences, the request for changing the APT address shall be throttled to one request in 4 hours.

**Comment by openBackhaul** [comment]
Potential Proposal for updating the APT client at APTP:
Additional service at APTP
```
/v1/update-apt-clients
  requestBody:
    apt-protocol
    apt-ip-address
    apt-tcp-port
    receive-acceptance-data-of-link-endpoint-service
    receive-performance-data-service
```
Basic service /v1/update-client might be an example for detailing the attributes.

**Comment by anacabbar** [comment]
Done
