### ISSUE TITLE
Throttling of services called by out of domain algorithms 

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/AutomatedLinkAcceptanceProxy#187]
All services that will not be applied by humans but by algorithms (e.g. services for link acceptance and connection state) should have a throttle function.

The dimensioning of the throttling should be configurable.

For example, the maximum number of requests to be executed in parallel or the maximum number of requests per time unit (e.g. second) could be used as a limit.
The limiting number should be stored in an instance of IntegerProfile.

The mechanism (incl. reference to the instance of IntegerProfile) should be described in 
- a note in the plantuml diagram
- a description at the path in the OAS (e.g. "description: "The number of requests to be executed in parallel shall be limited to the value stated in ..." ).

The throttling mechanism shall be completed by a meaningful error definition that includes clear advice to the client (e.g. "Try again after receiving a response").

**Comment by anacabbar** [comment]
List of Algorithms/Services which need throttling:

- [ ]  **/v1/provide-acceptance-data-of-link-endpoint :** Max. number of parallel requests
- [ ]  **/v1/provide-historical-pm-data-of-device** : Max. number of parallel requests
- [ ] **/v1/update-apt-clients** : Throttle period 
- [ ] /**v1/check-registered-availability-of-device** (service for checking connection status): Max. number of parallel requests? Internal List updation frequency?
- [ ] **service for showing status in LiveNetView** (if retrieving from 'live' is decided) : Max. number of parallel requests

**Comment by anacabbar** [comment]
* Configurable throttling parameters added in the form of integer profile instances
* Throttling described in OAS and diagrams
* As agreed in discussion with the TechM team, clear advice to the client (e.g. "Try again after receiving a response") will not be included in the error definitions, since these need to remain general and the error messages shall be clarifying enough for the client
