### ISSUE TITLE
Consolidation of the MWPP

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/AutomatedLinkAcceptanceProxy#189]
The MWPP://v1/provide-historical-pm-data-of-device shall be copied into the ALAP (incl. diagrams, entries in lists and OAS).

Throttling shall be applied, too.
Need and feasibility for making it asynchronous shall be evaluated.

**Comment by anacabbar** [comment]
* Service /v1/provide-historical-pm-data-of-device integrated into APTP
* Throttling applied
* Service made asynchronous
