### ISSUE TITLE
Separate service(s) for LiveNetView

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/AutomatedLinkAcceptanceProxy#190]
Separate service(s) for providing the information to be represented in the LiveNetView shall be defined.

As the user is waiting for the representation on the graphical user interface, quick provisioning shall be prioritized.
Certainly the services shall be synchronous (values inside the responseBody).
Separation into multiple requests that are to be individually initiated shall be considered.

Services shall address cache domain.
(Addressing the live domain shall be avoided. If unavoidable, request shall be separated from addressing cache domain and throttling shall be applied.)

**Comment by anacabbar** [comment]
Done:
/v1/provide-configuration-for-livenetview
/v1/provide-equipment-info-for-livenetview
/v1/provide-alarms-for-livenetview
/v1/provide-status-for-livenetview
