### ISSUE TITLE
Separate service for ConnectionStatus

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/AutomatedLinkAcceptanceProxy#191]
A separate service for supporting the ConnectionStatus UserCase shall be added.

The semantic of the service shall be clarified.
Presumably, it is not the connection status at the controller that is relevant to the customer (e.g. Axel).
Presumably, availability of data for reading in the MWDI is the relevant criteria.

Even if the APT GUI is representing it as "ConnectionStatus" the service at the ALAP shall be explicit in regard of the semantic.
Example: /v1/check-for-device-in-cache

Throttling shall be applied.

**Comment by openBackhaul** [comment]
Options for getting the ConnectionStatus information:
1) ALAP is attempting to GET a single attribute from the device data in the cache of the MWDI. If GETting the single attribute fails, ALAP in concluding the connection between Controller and device being down.
2) ALAP is reading the MWDI://v1/provide-list-of-connected-devices service and checks for the device being in the list.
3) ALAP is reading the MWDI://v1/provide-list-of-connected-devices service and stores the response for a "while" and checks for the device being in its stored list.
4) ALAP is reading the MWDI://v1/provide-list-of-connected-devices service and stores the response for a "long while", updates its internal list based on notifications provided by MWDI, and checks for the device being in its stored list.
5) A new MWDI://confirm-device-being-connected service that confirms an individual device being connected (Boolean).
6) A new MWDI://provide-connection-state-of-device service that allows to retrieving the connection state of a single device (enum{connected, connecting, unable_to_connect, no_mount_point_at_controller, .... }).

**Comment by anacabbar** [comment]
Ideally, ALAP/APTP should 

* Retrieve a list of the mount points known to the controller with their respective connection status (enum{connected, connecting, unable_to_connect, no_mount_point_at_controller, .... }) and store it internally for a while.

* Get notifications from MWDI about new/deleted mount points and about changes in the connection status of known mount points.
*  Update its internal list on a cyclic basis by regularly querying MWDI (updation frequency to be determied in an integer profile).

However, as of today MWDI is offering neither notifications of ControllerAttributeValueChanges (i.e. updates about the connected or disconnected devices) nor information about the connection status of mount points known to the controller.

These MWDI features are [requested](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/980) and will be used on the 3rd APTP iteration.

Meanwhile APTP v1.1.0 will implement the 3rd approach from the list above:
	3. ALAP is reading the MWDI://v1/provide-list-of-connected-devices service and stores the response for a "while" and checks for the device being in its stored list.

**Comment by anacabbar** [comment]
Done
