### ISSUE TITLE
string value for RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel shall be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AutomatedLinkAcceptanceProxy#197]
For formulating the value of inventory/position-of-modem-board in response body of /v1/provide-acceptance-data-of-link-endpoint, the procedure defined in https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/144#issuecomment-2007737888 is being used. 

For this, we require _"uuid" of the equipment_ in response-body of  _RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel_ which uses following url. 

> MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}?fields=equipment(contained-holder(occupying-fru;equipment-augment-1-0:holder-pac(vendor-label))) 

Currently as per issue https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/917, the response of above url doesnot contain "uuid" of equipment. 

Proposal 1:
  If the issue https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/917 is decided to include key attributes by default, we can close this issue as we get equipment uuid from response. 

On the other hand, if the response from MWDI/cache is not expected to have uuid by default, we can consider following proposal.
Proposal 2:
We can modify the fields filter by modifying the string-value of profile _RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel_ to below:
 

> equipment(_**uuid**_;contained-holder(occupying-fru;equipment-augment-1-0:holder-pac(vendor-label))) 

Kindly let me know your views.

**Comment by anacabbar** [comment]
_Proposal 2_ has been applied to the specification of APTP v1.1.0 : the string _RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition.HolderLabel_ has been changed to 
> uuid;equipment(contained-holder(occupying-fru;equipment-augment-1-0:holder-pac(vendor-label)))

However, the cache seems to also be already returning the uuid by default as describied in Proposal 1. Confirmation and documentation of this fact to be further tracked in [MWDI #917](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/917).
