### ISSUE TITLE
[Thoughts] Creation of the ForwardingList

### ISSUE THREAD

**Issue by anacabbar** [openBackhaul/AutomatedLinkAcceptanceProxy#33]
Forwarding - Individual to the ALAP:
EVENT [Request received by (individual) OperationServer ]: **/v1/provide-acceptance-data-of-link-endpoint**
REACTION [Requests that have to be sent] : **All indivual OperationClients of the MWDI**

**Comment by anacabbar** [comment]
## TODO: Potentially add Forwardings for configuring INDIVIDUAL subscriptions on NewRelease
[Thought: The ALAP does not offer subscriptions to other applications. only ProcessSnippet (?)]

**Comment by anacabbar** [comment]
TODO: Add Forwardings for transferring data to NewRelease
[Thoughts: 
* The ALAP does not store any data that would have to be transferred during upgrade process. 
* The ALAP learns its data calling OperationServers of the MWDI
* This forwarding is required for the future release of the ALAP to call the same OperationServers as the previous one(?)
 ]

**Comment by anacabbar** [comment]
TODO: Potentially add Forwardings for creating INDIVIDUAL subscriptions to NewRelease
[Thought:]
The ALAP does not subscribe for notifications at some 3rd application

**Comment by anacabbar** [comment]
TODO: Potentially add Forwardings for ending INDIVIDUAL subscriptions to OldRelease
[Thought:]
The ALAP does not subscribe for notifications at some 3rd application

**Comment by anacabbar** [comment]
TODO: All INDIVIDUAL service requests, which are updating an LTP, to be complemented
TODO: All INDIVIDUAL service requests, which are deleting an LTP, to be complemented
[Thought:]
The ALAP does neither update nor delete LTPs

**Comment by anacabbar** [comment]
TODO: All INDIVIDUAL service requests, which are updating an FC, to be complemented
TODO: All INDIVIDUAL service requests, which are updating an FC-Port, to be complemented
TODO: All INDIVIDUAL service requests, which are deleting an FC-Port, to be complemented
[Thought:]
The ALAP expects only a single request, that will always result in the same response.  The number of outputs and the reaction will never be altered.

**Comment by openBackhaul** [comment]
ForwardingList completed.
Forwardings for reading from MWDI added.
No subscriptions, so no subscriptions to be transferred to NewRelease or any other handling required.
Service requests for updating FC or FC-Port not required as all forwardings invariant.
