### ISSUE TITLE
Update ServiceList to include HttpClient OpenDaylight

### ISSUE THREAD

**Issue by anacabbar** [openBackhaul/AutomatedLinkAcceptanceProxy#37]
* Replace calling entire classes by more specific requests.
* Leave list of services for Config/Status under HttpClient MWDI.
* Add HttpClient OpenDaylight and list the corresponding services for Measurement Attributes.

**Comment by openBackhaul** [comment]
MWDI got a new design as the AttributeValueChanged notifications are not properly provided by the devices.
MWDI serves as a gateway to the live network (OpenDaylight), too.
So, status and measurement attributed to be read via MWDI, too.
ServiceList completed.
