### ISSUE TITLE
Update services for Equipment-ID and Equipment Details retrieval  

### ISSUE THREAD

**Issue by anacabbar** [openBackhaul/AutomatedLinkAcceptanceProxy#41]
The following two services in the actual list, envisioned to retrieve Equipment ID and Slot/Port number, must be respectively changed according to the latest/planned infomation model structure 

FROM:
/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac/ltp-augment-capability

 /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/equipment={uuid}?fields=name;actual-equipment(manufactured-thing(equipment-type;equipment-instance))

TO:
/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac

 /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/equipment={uuid}/holder={uuid}/holder-pac/sequence-id

**Comment by anacabbar** [comment]
* The LtpAugmentCapability class will be eliminated from the model by all vendors within the next two months
* The Equipment model will be extended (?) with the equipment-augment-class (as illustrated in
[Equipment](https://github.com/openBackhaul/equipment/blob/tsp/EquipmentAugment_1.0.0-tsi.230516.1120%2Boverview.1.png) ) thus containing a SequenceId which identifies the slot number.

**Comment by openBackhaul** [comment]
Done.
