### ISSUE TITLE
Correct typo in oas callback response

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/AutomatedLinkAcceptanceProxy#51]
remove the hyphen after manufactured-thing in line 3312:
![image](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/assets/57349523/753ab6f1-58b5-433d-bbd0-b8a033f48b04)
callback: RequestForProvidingAcceptanceDataCausesReadingTheRadioComponentIdentifiers

**Comment by openBackhaul** [comment]
" removed in two occurrences
