### ISSUE TITLE
OUTPUT fc-port list of RequestForProvidingAcceptanceDataCausesRetrievingSfpInformation might need a modification

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AutomatedLinkAcceptanceProxy#77]
In [config.json](https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/blob/develop/spec/AutomatedLinkAcceptanceProxy%2Bconfig.json) file / forwarding-domain / forwarding-construct = RequestForProvidingAcceptanceDataCausesRetrievingSfpInformation, the list of OUTPUT fc-ports contains duplicate entries of alap-1-0-0-op-c-is-mwdi-1-0-0-201 (under local-id 200 and 202). 

However, as per the specification, the operation-client alap-1-0-0-op-c-is-mwdi-1-0-0-201 is expected to be called twice (one for EquipmentUuid and other for WireInterfaceName), but I think, two entries of same operation-client in same FC would not be necessary. 

Proposal: We can remove one OUTPUT fc-port (local-id=202) and change the proceeding local-ids like op-c alap-1-0-0-op-c-is-mwdi-1-0-0-270 to local-id 202 and alap-1-0-0-op-c-is-mwdi-1-0-0-272 to local-id 203.

Kindly let me know your views.

**Comment by anacabbar** [comment]
Awaiting decission to be made in #122  before addressing this issue

**Comment by anacabbar** [comment]
Hi Iswaryaa,

After dissolving this Forwarding containing multiple subsequent requests, as agreed in Issue 122, there will be one separate ForwardingConstruct for each  call of  **alap-1-0-0-op-c-is-mwdi-1-0-0-201**, with respectively a single output-port:

**RequestForProvidingAcceptanceDataCausesRetrievingSfpInformation.EquipmentUuid**
and
**RequestForProvidingAcceptanceDataCausesRetrievingSfpInformation.WireInterfaceName** 

This issue would be thus solved. Please confirm that you find this correct before it is closed. 

Best Regards, Ana

**Comment by IswaryaaS** [comment]
Yes Ana, this solution would solve the problem. Hence closing the issue. Thanks for clarification.
